export const jobOptions = [
  { value: 'developer', label: 'Software Engineer' },
  { value: 'mobile_developer', label: 'Mobile Developer' },
  { value: 'frontend developer', label: 'Frontend Developer' },
  { value: 'backend developer', label: 'Backend Developer' },
  { value: 'full stack developer', label: 'Full-Stack Developer' },
  { value: 'full stack developer', label: 'Web Developer' },
  { value: 'full stack developer', label: 'Build Engineer' },
  { value: 'full stack developer', label: 'Machine Learning Engineer' },
  { value: 'full stack developer', label: 'Security Engineer' },
  { value: 'full stack developer', label: 'UX Engineer' },
  { value: 'full stack developer', label: 'Database Administrator' },
  { value: 'full stack developer', label: 'Embedded Engineer' },
  { value: 'full stack developer', label: 'Operations Developer' },
  { value: 'Engineering Manager', label: 'Engineering Manager' },
  { value: 'QA Engineer', label: 'QA/test Engineer' },
  { value: 'devops', label: 'DevOps' },
  { value: 'Software Architect', label: 'Software Architect' },
  { value: 'hardware_engineer', label: 'Hardware Engineer' },
  { value: 'mechanical engineer', label: 'Mechanical Engineer' },
  { value: 'Systems Engineer', label: 'Systems Engineer' },
  { value: 'designer', label: 'Designer' },
  { value: 'designer', label: 'Brand/Graphic Designer' },
  { value: 'User Researcher', label: 'User Researcher' },
  { value: 'Visual Designer', label: 'Visual/UI Designer' },
  { value: 'Visual Designer', label: 'UX Designer' },
  { value: 'Visual Designer', label: 'Product Designer' },
  { value: 'Creative Director', label: 'Creative Director' },
  { value: 'finance', label: 'Accounting' },
  { value: 'finance', label: 'Financial Management / Analysis' },
  { value: 'finance', label: 'General Management' },
  { value: 'human_resources', label: 'H.R.' },
  { value: 'office_manager', label: 'Office Administration' },
  { value: 'recruiter', label: 'Recruiter' },
  { value: 'recruiter', label: 'Recruiter Coordinator' },
  { value: 'recruiter', label: 'Sourcer' },
  { value: 'recruiter', label: 'People Ops Management' },
  { value: 'recruiter', label: 'People Ops Specialist' },
  { value: 'customer service', label: 'Customer Service' },
  { value: 'Operations manager', label: 'Operations Manager' },
  { value: 'sales', label: 'Sales' },
  { value: 'business development', label: 'Business Development' },
  { value: 'Manager Business Development', label: 'BD Manager' },
  { value: 'Account Manager', label: 'Account Manager' },
  { value: 'Sales Manager', label: 'Sales Manager' },
  { value: 'Sales Manager', label: 'Sales Operactions' },
  { value: 'Sales Manager', label: 'Customer Success Manager' },
  { value: 'Sales Manager', label: 'Sales Development Rep' },
  { value: 'marketing', label: 'Acquisition Marketing' },
  { value: 'marketing', label: 'Content Marketing' },
  { value: 'marketing', label: 'Community/Events Marketing' },
  { value: 'marketing', label: 'Marketing Analytics' },
  { value: 'marketing', label: 'Product Marketing' },
  { value: 'marketing', label: 'PR/ communications' },
  { value: 'marketing', label: 'Lifecycle/Email Marketing' },
  { value: 'Growth Hacking', label: 'Growth Hacker' },
  { value: 'Marketing Manager', label: 'Marketing Manager' },
  { value: 'Content Creator', label: 'Content Creator' },
  { value: 'CEO', label: 'CEO' },
  { value: 'CFO', label: 'CFO' },
  { value: 'CMO', label: 'CMO' },
  { value: 'COO', label: 'COO' },
  { value: 'cto', label: 'CTO' },
  { value: 'attorney', label: 'Attorney' },
  { value: 'business analyst', label: 'Business Analyst' },
  { value: 'data scientist', label: 'Data Scientist' },
  { value: 'data analytst', label: 'Data Analyst' },
  { value: 'data engineer', label: 'Data Engineer' },
  { value: 'product_manager', label: 'Product Manager' },
  { value: 'Project Manager', label: 'Project Manager' },
];
