export const ERROR_FINDING_COMPANIES = 'ERROR_FINDING_COMPANIES';
export const ERROR_COMPANY_ALREADY_EXISTS = 'ERROR_COMPANY_ALREADY_EXISTS';

export const ERROR_CREATING_COMPANY = 'ERROR_CREATING_COMPANY';
export const ERROR_FINDING_COMPANY = 'ERROR_FINDING_COMPANY';
export const ERROR_UPDATING_COMPANY = 'ERROR_UPDATING_COMPANY';

export const ERROR_UPLOADING_LOGO = 'ERROR_UPLOADING_LOGO';
