export const ERROR_FINDING_JOBS = 'ERROR_FINDING_JOBS';

export const ERROR_FINDING_JOB = 'ERROR_FINDING_JOB';
export const ERROR_CREATING_JOB = 'ERROR_CREATING_JOB';
export const ERROR_UPDATING_JOB = 'ERROR_UPDATING_JOB';
export const ERROR_DELETING_JOB = 'ERROR_DELETING_JOB';
