export const ERROR_FINDING_USERS = 'ERROR_FINDING_USERS';

export const ERROR_FINDING_USER = 'ERROR_FINDING_USER';
export const ERROR_CREATING_USER = 'ERROR_CREATING_USER';
export const ERROR_UPDATING_USER = 'ERROR_UPDATING_USER';
export const ERROR_DELETING_USER = 'ERROR_DELETING_USER';

/**
 * These constants are related more to authentication of a user
 * or seraching for a user using token or email.
 */
export const ERROR_EXPIRED_PASSWORD_RESET_TOKEN =
  'ERROR_EXPIRED_PASSWORD_RESET_TOKEN';

export const ERROR_PASSWORDS_DO_NOT_MATCH = 'ERROR_PASSWORDS_DO_NOT_MATCH';

export const ERROR_INVALID_EMAIL_OR_PASSWORD =
  'ERROR_INVALID_EMAIL_OR_PASSWORD';

export const ERROR_INVALID_INVITE_TOKEN = 'ERROR_INVALID_INVITE_TOKEN';

export const ERROR_USER_ALREADY_ADDED = 'ERROR_USER_ALREADY_ADDED';
