export const jobOptions = [
  { label: 'Software Engineer', value: 'Software Engineer' },
  { label: 'Mobile Developer', value: 'Mobile Developer' },
  { label: 'Frontend Developer', value: 'Frontend Developer' },
  { label: 'Backend Developer', value: 'Backend Developer' },
  { label: 'Full-Stack Developer', value: 'Full-Stack Developer' },
  { label: 'Web Developer', value: 'Web Developer' },
  { label: 'Build Engineer', value: 'Build Engineer' },
  { label: 'Machine Learning Engineer', value: 'Machine Learning Engineer' },
  { label: 'Security Engineer', value: 'Security Engineer' },
  { label: 'UX Engineer', value: 'UX Engineer' },
  { label: 'Database Administrator', value: 'Database Administrator' },
  { label: 'Embedded Engineer', value: 'Embedded Engineer' },
  { label: 'Operations Developer', value: 'Operations Developer' },
  { label: 'Engineering Manager', value: 'Engineering Manager' },
  { label: 'QA/test Engineer', value: 'QA/test Engineer' },
  { label: 'DevOps', value: 'DevOps' },
  { label: 'Software Architect', value: 'Software Architect' },
  { label: 'Hardware Engineer', value: 'Hardware Engineer' },
  { label: 'Mechanical Engineer', value: 'Mechanical Engineer' },
  { label: 'Systems Engineer', value: 'Systems Engineer' },
  { label: 'Designer', value: 'Designer' },
  { label: 'Brand/Graphic Designer', value: 'Brand/Graphic Designer' },
  { label: 'User Researcher', value: 'User Researcher' },
  { label: 'Visual/UI Designer', value: 'Visual/UI Designer' },
  { label: 'UX Designer', value: 'UX Designer' },
  { label: 'Product Designer', value: 'Product Designer' },
  { label: 'Creative Director', value: 'Creative Director' },
  { label: 'Accounting', value: 'Accounting' },
  {
    label: 'Financial Management / Analysis',
    value: 'Financial Management / Analysis'
  },
  { label: 'General Management', value: 'General Management' },
  { label: 'H.R.', value: 'H.R.' },
  { label: 'Office Administration', value: 'Office Administration' },
  { label: 'Recruiter', value: 'Recruiter' },
  { label: 'Recruiter Coordinator', value: 'Recruiter Coordinator' },
  { label: 'Sourcer', value: 'Sourcer' },
  { label: 'People Ops Management', value: 'People Ops Management' },
  { label: 'People Ops Specialist', value: 'People Ops Specialist' },
  { label: 'Customer Service', value: 'Customer Service' },
  { label: 'Operations Manager', value: 'Operations Manager' },
  { label: 'Sales', value: 'Sales' },
  { label: 'Business Development', value: 'Business Development' },
  { label: 'BD Manager', value: 'BD Manager' },
  { label: 'Account Manager', value: 'Account Manager' },
  { label: 'Sales Manager', value: 'Sales Manager' },
  { label: 'Sales Operactions', value: 'Sales Operactions' },
  { label: 'Customer Success Manager', value: 'Customer Success Manager' },
  { label: 'Sales Development Rep', value: 'Sales Development Rep' },
  { label: 'Acquisition Marketing', value: 'Acquisition Marketing' },
  { label: 'Content Marketing', value: 'Content Marketing' },
  { label: 'Community/Events Marketing', value: 'Community/Events Marketing' },
  { label: 'Marketing Analytics', value: 'Marketing Analytics' },
  { label: 'Product Marketing', value: 'Product Marketing' },
  { label: 'PR/ communications', value: 'PR/ communications' },
  { label: 'Lifecycle/Email Marketing', value: 'Lifecycle/Email Marketing' },
  { label: 'Growth Hacker', value: 'Growth Hacker' },
  { label: 'Marketing Manager', value: 'Marketing Manager' },
  { label: 'Content Creator', value: 'Content Creator' },
  { label: 'CEO', value: 'CEO' },
  { label: 'CFO', value: 'CFO' },
  { label: 'CMO', value: 'CMO' },
  { label: 'COO', value: 'COO' },
  { label: 'CTO', value: 'CTO' },
  { label: 'Attorney', value: 'Attorney' },
  { label: 'Business Analyst', value: 'Business Analyst' },
  { label: 'Data Scientist', value: 'Data Scientist' },
  { label: 'Data Analyst', value: 'Data Analyst' },
  { label: 'Data Engineer', value: 'Data Engineer' },
  { label: 'Product Manager', value: 'Product Manager' },
  { label: 'Project Manager', value: 'Project Manager' }
];

export default jobOptions;
